apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cubeapm.fullname" . }}
data:
  config.properties: |
    # CubeAPM Configuration Properties
    # Sensitive values are left empty and can be populated via secrets
    
    # Basic Configuration
    baseUrl={{ .Values.configVars.baseUrl }}
    envTag={{ .Values.configVars.envTag | default "" }}
    logLevel={{ .Values.configVars.logLevel }}
    shutdownDelay={{ .Values.configVars.shutdownDelay }}
    timeZone={{ .Values.configVars.timeZone }}
    
    # Database Configuration
    database.url={{ .Values.configVars.database.url }}
    
    # SMTP Configuration
    smtp.from={{ .Values.configVars.smtp.from | default "" }}
    smtp.url={{ .Values.configVars.smtp.url | default "" }}
    
    # Alert Manager Configuration
    alertmanager.charts.disable={{ .Values.configVars.alertmanager.charts.disable | default false }}
    alertmanager.jira.siteName={{ .Values.configVars.alertmanager.jira.siteName | default "" }}
    alertmanager.jira.token=
    alertmanager.jira.tokenExpiryDate={{ .Values.configVars.alertmanager.jira.tokenExpiryDate | default "" }}
    alertmanager.jira.userEmail={{ .Values.configVars.alertmanager.jira.userEmail | default "" }}
    alertmanager.oauth.pagerduty.appId={{ .Values.configVars.alertmanager.oauth.pagerduty.appId | default "" }}
    alertmanager.oauth.slack.token=
    alertmanager.opsgenie.tokens=
    
    # Authentication Configuration
    auth.database.url={{ .Values.configVars.auth.database.url | default "" }}
    auth.key.session=
    auth.oidc.github.clientId={{ .Values.configVars.auth.oidc.github.clientId | default "" }}
    auth.oidc.github.clientSecret=
    auth.oidc.google.clientId={{ .Values.configVars.auth.oidc.google.clientId | default "" }}
    auth.oidc.google.clientSecret=
    auth.session.lifespan={{ .Values.configVars.auth.session.lifespan }}
    auth.sysAdmins={{ .Values.configVars.auth.sysAdmins }}
    auth.defaultRole={{ .Values.configVars.auth.defaultRole }}
    
    # Cluster Configuration
    cluster.replicationFactor={{ .Values.cluster.replicationFactor | default 1 }}
    cluster.advertise.address={{ .Values.cluster.advertise.address | default "" }}
    cluster.advertise.allowInsecure={{ .Values.cluster.advertise.allowInsecure | default false }}
    cluster.port.distributor={{ .Values.cluster.port.distributor }}
    cluster.port.read={{ .Values.cluster.port.read }}
    cluster.port.write={{ .Values.cluster.port.write }}
    cluster.port.state={{ .Values.cluster.port.state }}
    
    # Collector Configuration
    collector.otlp.grpc.disable={{ .Values.collector.otlp.grpc.disable | default false }}
    collector.otlp.grpc.port={{ .Values.collector.otlp.grpc.port | default 4317 }}
    collector.otlp.http.disable={{ .Values.collector.otlp.http.disable | default false }}
    collector.otlp.http.port={{ .Values.collector.otlp.http.port | default 4318 }}
    collector.otlp.http.cors.origins={{ .Values.collector.otlp.http.cors.origins | default "*" }}
    collector.nr8t.disable={{ .Values.collector.nr8t.disable | default false }}
    collector.nr8t.port={{ .Values.collector.nr8t.port | default 4319 }}
    
    # Retention Configuration
    files.retention={{ .Values.configVars.files.retention }}
    logs.retention={{ .Values.configVars.logs.retention }}
    logs.backup.destination={{ .Values.configVars.logs.backup.destination | default "" }}
    logs.backup.concurrency={{ .Values.configVars.logs.backup.concurrency | default 1 }}
    logs.backup.s3.customEndpoint={{ .Values.configVars.logs.backup.s3.customEndpoint | default "" }}
    logs.backup.s3.forcePathStyle={{ .Values.configVars.logs.backup.s3.forcePathStyle | default false }}
    logs.backup.s3.storageClass={{ .Values.configVars.logs.backup.s3.storageClass | default "" }}
    logs.datadog.streamFields={{ .Values.configVars.logs.datadog.streamFields | default "" }}
    logs.datadog.ignoreFields={{ .Values.configVars.logs.datadog.ignoreFields | default "" }}
    logs.newrelic.streamFields={{ .Values.configVars.logs.newrelic.streamFields | default "" }}
    logs.newrelic.ignoreFields={{ .Values.configVars.logs.newrelic.ignoreFields | default "" }}
    metrics.retention={{ .Values.configVars.metrics.retention }}
    metrics.updateInterval={{ .Values.configVars.metrics.updateInterval }}
    traces.retention={{ .Values.configVars.traces.retention }}
    traces.slowQueryThreshold={{ .Values.configVars.traces.slowQueryThreshold }}
    
    # Tracegen Configuration
    tracegen.disable={{ .Values.configVars.tracegen.disable | default false }}
    
    # Service Configuration
    service.port={{ .Values.service.port }}
    service.internalPort={{ .Values.service.internalPort }}
    service.admin.enabled={{ .Values.service.admin.enabled | default false }}
    service.admin.port={{ .Values.service.admin.port | default 3199 }}
    service.admin.token=
    
    # Token (will be populated via secret)
    token={{ .Values.configVars.token }}
    
  {{- if .Values.configVars.alerts.configFile }}
  alerts.yml: |
    {{- toYaml .Values.configVars.alerts.configFile | nindent 4 }}
  {{- end }}
  {{- if .Values.configVars.metrics.customLabelsConfigFile }}
  metrics.yml: |
    {{- toYaml .Values.configVars.metrics.customLabelsConfigFile | nindent 4 }}
  {{- end }}
  {{- if .Values.configVars.traces.customIndexesConfigFile }}
  traces.yml: |
    {{- toYaml .Values.configVars.traces.customIndexesConfigFile | nindent 4 }}
  {{- end }}
  {{- if .Values.configVars.metrics.slo.configFile }}
  slo.yml: |
    {{- toYaml .Values.configVars.metrics.slo.configFile | nindent 4 }}
  {{- end }}
  {{- if .Values.collector.spanTransformsConfigFile }}
  span_transforms.yml: |
    {{- toYaml .Values.collector.spanTransformsConfigFile | nindent 4 }}
  {{- end }}
