apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cubeapm.fullname" . }}
data:
  {{- if .Values.configVars.metrics.customLabelsConfigFile }}
  metrics.yml: |
    {{- toYaml .Values.configVars.metrics.customLabelsConfigFile | nindent 4 }}
  {{- end }}
