apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cubeapm.fullname" . }}
data:
  {{- if .Values.alertmanager.config }}
  alertmanager.yml: |
    {{- toYaml .Values.alertmanager.config | nindent 4 }}
  {{- range $key, $value := .Values.alertmanager.templates }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- end }}
