{{- if .Values.ingressTraces.nr8t.enabled -}}
{{- if .Values.collector.nr8t.disable -}}
{{- fail "collector.nr8t.disable must also be set to false if ingressTraces.nr8t.enabled is set to true" }}
{{- end }}
{{- $fullName := include "cubeapm.fullname" . -}}
{{- $svcPort := .Values.collector.nr8t.port -}}
{{- if and .Values.ingressTraces.nr8t.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingressTraces.nr8t.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingressTraces.nr8t.annotations "kubernetes.io/ingress.class" .Values.ingressTraces.nr8t.className }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName | trunc 51 | trimSuffix "-" }}-traces-nr8t
  labels:
    {{- include "cubeapm.labels" . | nindent 4 }}
  {{- with .Values.ingressTraces.nr8t.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingressTraces.nr8t.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingressTraces.nr8t.className }}
  {{- end }}
  {{- if .Values.ingressTraces.nr8t.tls }}
  tls:
    {{- range .Values.ingressTraces.nr8t.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressTraces.nr8t.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
