{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cubeapm.serviceAccountName" . }}
  labels:
    {{- include "cubeapm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "cubeapm.imagePullSecrets" . }}
{{- end }}
