apiVersion: v1
kind: Service
metadata:
  name: {{ include "cubeapm.fullname" . | trunc 54 | trimSuffix "-" }}-headless
  labels:
    {{- include "cubeapm.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: http-internal
      protocol: TCP
      name: http-internal
  selector:
    {{- include "cubeapm.selectorLabels" . | nindent 4 }}
