{{- if .Values.serviceTraces.enabled -}}
{{- $fullName := include "cubeapm.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName | trunc 56 | trimSuffix "-" }}-traces
  labels:
    {{- include "cubeapm.labels" . | nindent 4 }}
  {{- if .Values.serviceTraces.annotations }}
  annotations:
    {{- toYaml .Values.serviceTraces.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceTraces.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: http-internal
      protocol: TCP
      # appProtocol:
      name: http-internal
    {{- if not .Values.collector.otlp.grpc.disable }}
    - port: {{ .Values.collector.otlp.grpc.port }}
      targetPort: otlp-grpc
      protocol: TCP
      # appProtocol:
      name: otlp-grpc
    {{- end }}
    {{- if not .Values.collector.otlp.http.disable }}
    - port: {{ .Values.collector.otlp.http.port }}
      targetPort: otlp-http
      protocol: TCP
      # appProtocol:
      name: otlp-http
    {{- end }}
    {{- if not .Values.collector.nr8t.disable }}
    - port: {{ .Values.collector.nr8t.port }}
      targetPort: nr8t
      protocol: TCP
      # appProtocol:
      name: nr8t
    {{- end }}
  selector:
    {{- include "cubeapm.selectorLabels" . | nindent 4 }}
{{- end }}
