apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cubeapm.fullname" . }}
  labels:
    {{- include "cubeapm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "cubeapm.fullname" . | trunc 54 | trimSuffix "-" }}-headless
  replicas: {{ .Values.cluster.podCount }}
  selector:
    matchLabels:
      {{- include "cubeapm.selectorLabels" . | nindent 6 }}
  # minReadySeconds: 10
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podCustomAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cubeapm.selectorLabels" . | nindent 8 }}
        {{- with .Values.podCustomLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "cubeapm.imagePullSecrets" . }}
      serviceAccountName: {{ include "cubeapm.serviceAccountName" . }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "cubeapm.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "cubeapm.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--data-dir=/var/lib/cubeapm/data"
            - "--config-file=/etc/cubeapm/config.properties"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http-internal
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
            - name: http-private
              containerPort: {{ .Values.service.privatePort }}
              protocol: TCP
            {{- if .Values.service.admin.enabled }}
            - name: http-admin
              containerPort: {{ .Values.service.admin.port }}
              protocol: TCP
            {{- end }}
            {{- if gt (int .Values.cluster.podCount) 1 }}
            - name: cluster-dist
              containerPort: {{ .Values.cluster.port.distributor }}
              protocol: TCP
            - name: cluster-read
              containerPort: {{ .Values.cluster.port.read }}
              protocol: TCP
            - name: cluster-write
              containerPort: {{ .Values.cluster.port.write }}
              protocol: TCP
            - name: cluster-state-t
              containerPort: {{ .Values.cluster.port.state }}
              protocol: TCP
            - name: cluster-state-u
              containerPort: {{ .Values.cluster.port.state }}
              protocol: UDP
            {{- end }}
            {{- if not .Values.collector.otlp.grpc.disable }}
            - name: otlp-grpc
              containerPort: {{ .Values.collector.otlp.grpc.port }}
              protocol: TCP
            {{- end }}
            {{- if not .Values.collector.otlp.http.disable }}
            - name: otlp-http
              containerPort: {{ .Values.collector.otlp.http.port }}
              protocol: TCP
            {{- end }}
            {{- if not .Values.collector.nr8t.disable }}
            - name: nr8t
              containerPort: {{ .Values.collector.nr8t.port }}
              protocol: TCP
            {{- end }}
          env:
            # {{- range $host := .Values.ingress.hosts }}
            # {{- range .paths }}
            # http{{ if $.Values.ingress.tls }}s{{ end }}://{{ $host.host }}{{ .path }}
            # {{- end }}
            # {{- end }}
            # - name: CUBE_BASE_URL
            #   value: {{ required "A valid configVars.baseUrl is required!" .Values.configVars.baseUrl }}
            # add extraEnvs
            {{- with .Values.extraEnvs }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/cubeapm
          {{- if .Values.persistence.enabled }}
          {{- if .Values.persistence.existingClaim }}
            - name: cubeapm-data-existing-claim
          {{- else }}
            - name: cubeapm-data
          {{- end }}
          {{- else }}
            - name: cubeapm-data-volume
          {{- end }}
              mountPath: /var/lib/cubeapm/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cubeapm.fullname" . }}
      {{- if (not .Values.persistence.enabled) }}
        - name: cubeapm-data-volume
          emptyDir: {}
      {{- else if .Values.persistence.existingClaim }}
        - name: cubeapm-data-existing-claim
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}

{{- if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: cubeapm-data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- $storageClass := default .Values.persistence.storageClass .Values.global.storageClass -}}
      {{- if $storageClass -}}
      {{- if (eq "-" $storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ $storageClass }}
      {{- end }}
      {{- end }}
{{- end }}
